Python_language-$(CONFIG_PK_PYTHON_BISCUITOS)		+= BiscuitOS-Python/

PACKAGE_MAKEDIR := $(patsubst %/, $(srctree)/package/language/Python/%/Makefile, $(Python_language-y))

include $(PACKAGE_MAKEDIR)
