vmamerge-$(CONFIG_PK_BISCUITOS_VMA_MERGE_LAYOUT0_DISCONNECT)	+= BiscuitOS-vma-merge-layout0-disconnect/

PACKAGE_MAKEDIR := $(patsubst %/, $(srctree)/package/memory-mapping/BiscuitOS-vma-merge/%/Makefile, $(vmamerge-y))

include $(PACKAGE_MAKEDIR)
