x86_Regsex-$(CONFIG_PK_CPUID.01H_DEFAULT)	+= CPUID.01H-Default/

PACKAGE_MAKEDIR := $(patsubst %/, $(srctree)/package/Register/x86/CPUID/CPUID.01H/%/Makefile, $(x86_Regsex-y))

include $(PACKAGE_MAKEDIR)
