# /etc/fstab
# static file system information
#
# This file is not used by the kernel, but rather by mount(8) and umount(8)
# (and some day fsck(8)).  Comment lines have "#" in the first column.
# Entries that are to be ignored should have "none" in the directory field,
# and have type "ignore" or options "xx".  Frequency and pass are numeric
# fields for dump(8) and fsck(8) that are not used yet in Linux.  You can
# leave them empty if want.

# device	directory	type	options		freq pass

