x86_Regsew-$(CONFIG_PK_CPUID.80000008H_DEFAULT)	+= CPUID.80000008H-Default/

PACKAGE_MAKEDIR := $(patsubst %/, $(srctree)/package/Register/x86/CPUID/CPUID.80000008H/%/Makefile, $(x86_Regsew-y))

include $(PACKAGE_MAKEDIR)
