vmamerge-$(CONFIG_PK_BISCUITOS_VMA_MERGE_CASE0)	+= BiscuitOS-vma-merge-case0/

PACKAGE_MAKEDIR := $(patsubst %/, $(srctree)/package/memory-mapping/BiscuitOS-vma-merge/%/Makefile, $(vmamerge-y))

include $(PACKAGE_MAKEDIR)
