#! /bin/sh -
# Intro v0.98 - system for viewing introductory-type files

intro=`basename $0`

cat <<!!

Welcome to Linux v0.98.  This program will allow you to view the
various documentation files on this disk, which will help guide you
through the process of installing Linux on your computer.

To access the various files, just type the name at the prompt.  To get
a listing of the files available, type '?'.

To get out of this system, type 'quit' at the prompt.

!!

echo Available files:
ls /INSTALL/docs
echo quit

while [ 1 ]; do
	echo
	echo -n "Choice (? for options): "
	read ans
	if [ $ans ]; then
		if [ $ans = \? ]; then
			echo
			ls /INSTALL/docs
			echo quit
		elif [ $ans = quit ]; then
			echo
			exit 0
		elif [ -e /INSTALL/docs/$ans ]; then
			echo
			more /INSTALL/docs/$ans
		else
			echo
			echo "Sorry, invalid command."
		fi
	fi
done

exit 1
