#!/bin/bash

# This is a qemu-ifup script for bridging.
# You can use it when starting a KVM guest with bridge mode network.
# set your bridge name
#
# (C) 2019.09.06 BiscuitOS <buddy.zhang@aliyun.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#

[ ! -n "$1" ] && echo "Unknown NetWork Configure" && exit 0
echo "Configure BiscuitOS Networking $1........"
echo "Default Bridge bsBridge0 and Default Tap $1"

# Tap
TAP=bsTap0
# Bridge
BRIDGE=bsBridge0
IP=
MASK=
AIP=192
BIP=88
CIP=28
DIP=88
NIC=
GW=

# Check whether special net device exist
# @$1: Device name (Include: Bridge, Eth, Tap ...etc)
# 
# Common command:
# -> ls /sys/class/net
# -> ifconfig | grep "Link" | awk '{print $1}'
nic_check()
{
	local nics=`ls /sys/class/net`
	for nic in ${nics}
	do
		# Find special device nic
		[ ${nic}X = ${1}X ] && return 0		
	done
	# No fond
	return 1
}

#
# Obtain valid netcard and IP
# Current IP addr
# -> ifconfig | grep 'inet addr:' | grep -v '127.0.0.1' | cut -d: -f2 | awk '{print $1}'
#
get_current_ip_nic()
{
	nics=$(route -n | grep ^0.0.0.0 | awk '{print $8}')
	for nic in ${nics}
	do
		ip=$(ifconfig $nic | grep -E 'inet\s+' | sed -E -e 's/inet\s+\S+://g' | awk '{print $1}')
		ping -I ${nic} www.baidu.com -c1 -W1 -w 0.1 > /dev/null 2>&1
		[ $? -eq 0 ] && NIC=${nic} && IP=${ip} && return 0
	done

	[ -z ${NIC} ] && echo "Can't find valid NetCard." && return 1
	[ -z ${IP} ] && echo "Invalid IP for ${NIC}" && return 1
}

# Calculate AIP, BIP, CIP, DIP field. Default MASK is 255.255.255.0
# 
ip_calculate()
{
	# A class IP Address field
	AIP=${IP%%.*}
	# D class IP Address field
	DIP=${IP##*.}

	tmpip1=${IP%.*}
	tmpip2=${IP#*.}

	# B class IP Address field
	uBIP=${tmpip2%%.*}
	# User private B class field
	[ ${uBIP} -eq ${BIP} ] && BIP=$((${BIP}-1))
	# C class IP Address field
	CIP=${tmpip1##*.}

	# MASK
	MASK=255.255.255.0
}


# Establish Connect
#
establish_net()
{
	# Establish bridge on Host
	nic_check ${BRIDGE} ; [ $? = 1 ] && sudo brctl addbr ${BRIDGE}

	# Establish TAP on Host
	nic_check ${TAP} ; [ $? = 1 ] && sudo tunctl -b -t ${TAP}
}

# Search a unused IP
allocate_ip()
{
	for i in {1..254}
	do
		ping -c 1 -w 1 ${AIP}.${BIP}.${CIP}.${i} > /dev/null 2>&1
		[ $? -ne 0 ] && DIP=${i} && return 0
	done
	return 1
}

# Default gw
default_gw()
{
	echo `route -n | grep ${NIC} | grep UG | awk '{print $2}'` > .tmp
	uGW=`cat .tmp`
	GW=${uGW%% *}
}

# Get Current IP and NIC
get_current_ip_nic ; [ $? = 1 ] && exit 0

# Calculate IP: A,B,C,D field and Mask
ip_calculate

# Establish TAP and Birdge
establish_net

# Enable Bridge and Tap
sudo ifconfig ${BRIDGE} up
sudo ifconfig ${TAP} up

# Insert TAP into Bridge
sudo brctl addif ${BRIDGE} ${TAP} > /dev/null 2>&1

# Allocate IP for Birdge
sudo ifconfig ${BRIDGE} ${AIP}.${BIP}.1.1/24
# Allocate IP for TAP
allocate_ip 
sudo ifconfig ${TAP} ${AIP}.${BIP}.${CIP}.${DIP}/24 netmask ${MASK}

# Setup Gatway
# obtain default gw for $NIC
default_gw
[ ! ${GW} ] && GW=${AIP}.${BIP}.1.1
# Add all IP field into default gatway
sudo route add -net 0.0.0.0 netmask 0.0.0.0 gw ${GW}
# Add Tap into Bridge
sudo route add -net ${AIP}.${BIP}.0.0 gw ${AIP}.${BIP}.1.1 netmask 255.255.0.0

# Tun on forward on Host
sudo echo 1 > /proc/sys/net/ipv4/ip_forward

# Setup NAT
iptables -t nat -A POSTROUTING -o ${NIC} -j MASQUERADE
