#!/bin/bash

# This is a qemu-ifup script for bridging.
# You can use it when starting a KVM guest with bridge mode network.
# set your bridge name
#
# (C) 2019.09.06 BiscuitOS <buddy.zhang@aliyun.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#

[ ! -n "$1" ] && echo "Unknown NetWork Configure" && exit 0
echo "[BiscuitOS] Configure BiscuitOS Networking: $1"

# Tap
TAP=$1
# Bridge
BRIDGE=bsBridge0

NET_CFG=/tmp/BiscuitOS_NetCfg.cfg
[ ! -f ${NET_CFG} ] && echo "${NET_CFG} doesn't exist" && exit 0
uGW=`sed -n 2p ${NET_CFG}`
uBG=`sed -n 1p ${NET_CFG}`
uIC=`sed -n 3p ${NET_CFG}`
DEFAULT_GW=${uGW#* }
BRIDGE_IP=${uBG#* }
NIC=${uIC#* }

IP=${BRIDGE_IP}
MASK=
AIP=
BIP=
uBIP=
CIP=
DIP=
NIC=
GW=

# Check whether special net device exist
# @$1: Device name (Include: Bridge, Eth, Tap ...etc)
# 
# Common command:
# -> ls /sys/class/net
# -> ifconfig | grep "Link" | awk '{print $1}'
nic_check()
{
	local nics=`ls /sys/class/net`
	for nic in ${nics}
	do
		# Find special device nic
		[ ${nic}X = ${1}X ] && return 0		
	done
	# No fond
	return 1
}

#
# Obtain valid netcard and IP
# Current IP addr
# -> ifconfig | grep 'inet addr:' | grep -v '127.0.0.1' | cut -d: -f2 | awk '{print $2}'
#
get_current_ip_nic()
{
	nics=$(route -n | grep ^0.0.0.0 | awk '{print $8}')
	for nic in ${nics}
	do
		ip=$(ifconfig $nic | grep -E 'inet\s+' | sed -E -e 's/inet\s+\S+://g' | awk '{print $2}')
		ping -I ${nic} www.baidu.com -c1 -W1 -w 0.1 > /dev/null 2>&1
		[ $? -eq 0 ] && NIC=${nic} && IP=${ip} && return 0
	done

	[ -z ${NIC} ] && echo "Can't find valid NetCard." && return 1
	[ -z ${IP} ] && echo "Invalid IP for ${NIC}" && return 1
}

# 
# Check NIC whether configure IP
check_ip()
{
	ip=$(ifconfig $1 | grep -E 'inet\s+' | sed -E -e 's/inet\s+\S+://g' | awk '{print $2}')
	[ ! ${ip} ] && return 1
	return 0
}

# Calculate AIP, BIP, CIP, DIP field. Default MASK is 255.255.255.0
# 
ip_calculate()
{
	# A class IP Address field
	AIP=${IP%%.*}
	# D class IP Address field
	DIP=${IP##*.}

	tmpip1=${IP%.*}
	tmpip2=${IP#*.}

	# B class IP Address field
	BIP=${tmpip2%%.*}
	# C class IP Address field
	CIP=${tmpip1##*.}

	# MASK
	MASK=255.255.255.0
}


# Establish Connect
#
establish_net()
{
	# Establish TAP on Host
	nic_check ${TAP} ; [ $? = 1 ] && sudo tunctl -b -t ${TAP}
}

# Search a unused IP
allocate_ip()
{
	for i in {1..254}
	do
		ping -c 1 -w 1 ${AIP}.${BIP}.${CIP}.${i} > /dev/null 2>&1
		[ $? -ne 0 ] && DIP=${i} && return 0
	done
	return 1
}

# Default gw
default_gw()
{
	echo `route -n | grep ${NIC} | grep UG | awk '{print $2}'` > .tmp
	uGW=`cat .tmp`
	GW=${uGW%% *}
}

# Calculate IP: A,B,C,D field and Mask
ip_calculate

# Establish TAP
establish_net

# Allocate IP for TAP
allocate_ip 
sudo ifconfig ${TAP} ${AIP}.${BIP}.${CIP}.${DIP}/24 netmask ${MASK} promisc up

# Insert TAP into Bridge
sudo brctl addif ${BRIDGE} ${TAP}

# Add Tap into Bridge
# sudo route add -net ${AIP}.${BIP}.${CIP}.${DIP} gw ${BRIDGE_IP} netmask 255.255.0.0

# Store Netwrok configure information
cat << EOF >> ${NET_CFG}
[${TAP}] ${AIP}.${BIP}.${CIP}.${DIP}
EOF
